services:
  backend:
    build:
      context: backend/
      dockerfile: ./Dockerfile
      target: dev
    container_name: backend
    command: flask --app books run --host 0.0.0.0 --debug
    volumes:
      - ./backend:/app
    networks:
      - backend
    ports:
      - 8000:5000
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  backend:
    name: backend_network
