services:
  backend:
    build:
      context: backend/
      dockerfile: ./Dockerfile
      target: prod
    container_name: backend
    networks:
      - backend
    ports:
      - 8000:8000
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  backend:
    name: backend_network
